export const CREATE_USER = "CREATE_USER";
export const LOGIN = "LOGIN";
export const ERROR_MESSAGE = "ERROR_MESSAGE";

export const GET_DISPATCH_INFO = "GET_DISPATCH_INFO";
export const SEARCH = "SEARCH";
export const EXPORT = "EXPORT";
export const ADD_SOURCE_DESTINATION_TRANSPORTER =
  "ADD_SOURCE_DESTINATION_TRANSPORTER";
export const GET_SOURCE_CODE = "GET_SOURCE_CODE";
export const GET_DESTINATION_CODE = "GET_DESTINATION_CODE";
export const GET_TRANSPORTER_CODE = "GET_TRANSPORTER_CODE";
export const ADD_NEW_DISPATCH = "ADD_NEW_DISPATCH";
